version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 20
  ignore:
  - dependency-name: balanced-match
    versions:
    - 1.0.1
  - dependency-name: chai
    versions:
    - 4.3.2
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 20
  ignore:
  - dependency-name: node
    versions:
    - 15.12.0.pre.alpine
    - 15.13.0.pre.alpine
    - 15.7.0.pre.alpine
    - 15.9.0.pre.alpine
