name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '37 5 * * *'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: docker build -t dude-wheres-my-stocks .

    - name: Run unit tests
      run: docker run --init --rm dude-wheres-my-stocks npm test

    - name: Run e2e tests
      env:
        FINNHUB_API_KEY: ${{ secrets.FINNHUB_API_KEY }}
      run: docker run --rm --env FINNHUB_API_KEY dude-wheres-my-stocks npm run test:e2e
